### **Array**


In [58]:
from array import *


val = array("i", [1,2,3,4,5,6,7,8,9])
print(val)

for i in range(0,6):
    print(val[i] , end= " , ")

print("\n") 
### enhence for loop
for i in val:
    print(i, end= ",,")

print("\n")
print(val.typecode)

print("\n")
# val.reverse()

for i in val:
    print(i, end=" , ")



array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])
1 , 2 , 3 , 4 , 5 , 6 , 

1,,2,,3,,4,,5,,6,,7,,8,,9,,

i


1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 

In [59]:
val.insert(1,50) ### Replace Element
val.append(100) ### Append Element In Last
val[2] = 300 ### Override the Element
for i in val:
    print(i, end=" , ")

1 , 50 , 300 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 100 , 

In [60]:
copyarray = array(val.typecode, (x*2 for x in val) )
print(copyarray)
print("\n")
copyarray.pop(2) ### Delete Which Element using Index in Pop
copyarray.remove(100) ### Delete Which Element using possible 
print("\n")
print(copyarray)

array('i', [2, 100, 600, 6, 8, 10, 12, 14, 16, 18, 200])




array('i', [2, 6, 8, 10, 12, 14, 16, 18, 200])


### **Slicing in Array**

In [61]:
abc = copyarray[2:5]
abc = copyarray[2:-2]
abc = copyarray[::-1]
print(abc)

array('i', [200, 18, 16, 14, 12, 10, 8, 6, 2])


In [65]:
arr1 = array("i", [])
n = int(input("Please enter a number:- "))

for i in range(0,n):
    arr1.append(int(input("Enter Next Number:- ")))

for x in arr1:
    print(x, end=" ")

1 2 3 4 5 

In [75]:
abc = val

print(abc)

index = abc.index(300)
print(index)

array('i', [1, 50, 300, 3, 4, 5, 6, 7, 8, 9, 100])
2


In [106]:
import numpy as np

In [116]:
arr = np.array([1,2,3,4,5.6] , float)

for i in arr:
    print(i,  end=" ")

1.0 2.0 3.0 4.0 5.6 

In [ ]:
earr = linspace(10,20,3) # Equal Size

for i in earr:
    print(i , end= " ")

10.0 15.0 20.0 

In [125]:
arr2 = arange(10,20, 4)

for i in arr2:
    print(i , end=" ")

10 14 18 

In [126]:
arr3 = logspace(5, 20, 4)
for i in arr3:
    print(i)

100000.0
10000000000.0
1000000000000000.0
1e+20


In [133]:
arr4 = zeros(5)
for i in arr4:
    print(i)

arr5 = ones(5)
for i in arr5:
    print(i , end=", ")

arr6 = full(5,5)
for i in arr6:
    print(i)

0.0
0.0
0.0
0.0
0.0
1.0, 1.0, 1.0, 1.0, 1.0, 5
5
5
5
5


### **Multi-Dimensional Array**

In [135]:
zero = array(10)
print(zero)

10


In [136]:
oned = array([2,3,4,5,6])
print(oned)

[2 3 4 5 6]


In [138]:
twod = array([[1,3,4,5],[5,6,7,8],[3,5,352,33]])
print(twod)

[[  1   3   4   5]
 [  5   6   7   8]
 [  3   5 352  33]]


In [140]:
three_d = array([[[2,3,4,5],[45,6,3,22]],[[54,53,2,2],[3,5,2,0]]])
print(three_d)

[[[ 2  3  4  5]
  [45  6  3 22]]

 [[54 53  2  2]
  [ 3  5  2  0]]]
